#!/bin/bash

#reset rules

iptables -F
iptables -X

iptables -t nat -F
iptables -t nat -X

iptables -t mangle -F
iptables -t mangle -X

#On drop le trafic entrant, sortant, et le forward

iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#et on set ce qu'on accepte

#connexion deja etablis
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

#loopback (boucle local)
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

#Protection des scan
iptables -A INPUT -p tcp -m multiport ! --dports 80,443,2222 -j LOG -m recent --set -m limit --limit 1/min --limit-burst 1
iptables -A INPUT -p tcp -m recent --update --seconds 3600 --hitcount 1 -j DROP
iptables -A INPUT -p udp -m multiport ! --dports 80,443,2222 -m recent --set -m limit --limit 1/min --limit-burst 1  -j LOG
iptables -A INPUT -p udp -m recent --update --seconds 3600 --hitcount 1 -j DROP


#ping

iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT

#ssh
iptables -A INPUT -p tcp		--dport 2222		-j ACCEPT

#http
iptables -A OUTPUT -p tcp		--dport 80		-j ACCEPT
iptables -A INPUT -p tcp		--dport 80		-j ACCEPT

#https
iptables -A OUTPUT -p tcp		--dport 443		-j ACCEPT
iptables -A INPUT -p tcp		--dport 443		-j ACCEPT

#DNS

iptables -A OUTPUT -p tcp		--dport 53		-j ACCEPT
iptables -A OUTPUT -p udp		--dport 53		-j ACCEPT
iptables -A INPUT -p tcp		--sport 53		-j ACCEPT
iptables -A INPUT -p udp		--sport 53		-j ACCEPT


iptables -A OUTPUT -m state --state NEW,ESTABLISHED -j ACCEPT
